### ISSUE TITLE
Missing: movecursor to center of focused window

### ISSUE THREAD

**Issue by Acumane** [dawsers/hyprscroller#11]
Last issue for now, heh

Without the plugin and `follow_mouse = 1`, the cursor is moved to the center of windows focused via keyboard. I can't reproduce this with the plugin enabled. It's sorely missed, since focus stolen on this layout by a distant cursor feels especially jarring

**Comment by dawsers** [comment]
You are totally right. When manually calling the dispatch (keyboard, not mouse movement), cursor should go to the newly focused window. Hyprland's layouts position it at the center of the newly focused window. I will fix that. What I don't know is if I should set the cursor at the center, or at the last known position for that window (if that is easy to do without changing too much code!).

**Comment by dawsers** [comment]
BTW, one thing that annoys me is I cannot really use `follow_mouse = 1`, which would be my preference, because if I have many windows and I change focus with the mouse crossing the edge of the screen, suddenly I am focusing on two or three windows beyond that edge. The reason this happens is Hyprland doesn't know there may be windows outside the screen, so the mouse focusing dispatch is called repeatedly. Nothing happens if all your windows fit in the screen, like in the default layouts, but as soon as you have several more windows outside, you're gone...fast.

**Comment by dawsers** [comment]
This has been fixed in fa8f73e81e3bd7d503f12b3568000460781ba2a9

Thanks for the report! I have never used the default layouts, so sometimes I am unaware of the default behavior.
