### ISSUE TITLE
`resizeactive`, `fullscreen` doesn't work on floating windows

### ISSUE THREAD

**Issue by Acumane** [dawsers/hyprscroller#13]
^

**Comment by dawsers** [comment]
Floating windows are not managed by a layout plugin, they are floating. When you make a window float, it is removed from the layout.

**Comment by Acumane** [comment]
To be clear, this is a regression; there's no way to resize floating windows without a mouse when using this plugin.  

`IHyprLayout` looks like it supports floating windows. Is this really a limitation of the Plugin API?

**Comment by dawsers** [comment]
When you make a window float, the compositor calls `onWindowRemovedTiling()` and the window leaves the control of the layout plugin. When you "unfloat" the window, the compositor calls `onWindowCreatedTiling()`, same as when you create a new window. So floating windows are not under the control of the plugin, they are removed from the layout by a higher instance, and that makes sense, because a floating window is not tiled.

**Comment by dawsers** [comment]
Like you said, `IHyprLayout` implements all the support functions for layout plugins, so it also takes care of calling the corresponding functions when things like floating a window happen. It will call `onWindowRemovedTiling()` and then manage the floating window until it stops being a floating window (and call `onWindowCreateTiling()` then). Of course, a plugin could override all these functions and re-implement all the functionality of `IHyprLayout`, it could even override parts of the compositor (as `hyprexpo` does), but it is out of the scope of a layout plugin to do all that, and generally not the smartest thing to do given all the changes happening upstream daily.

**Comment by Acumane** [comment]
DwindleLayout implements `IHyprLayout`. `resizeactive` and `fullscreen` dispatchers work on floating windows just fine

**Comment by dawsers** [comment]
*hyprscroller* also implements `resizeActiveWindow()`, but only for windows under the control of the layout, which floating windows are not, and the same goes for full screen mode of floating windows. Dwindle instead tries to "do something" with windows that are not under its control, and I could do the same. If you look at the code in Dwindle, you will see things like "massive hack" (``fullscreenRequestForWindow()`) because it needs to create fake nodes just to figure out what to do with a window that has nothing to do with the layout and is asking for a "maximized" mode. iHyprLayout also has references to Dwindle (!) in `IHyprLayout::moveActiveWindow()` because the code of those two has been intertwined from the beginning, and moved back and forth. If you ask me, that is not clean, but of course I can also copy all that code, and it will work. But then every layout will need to copy all that code, which is irrelevant to the layout, and update it every time a change happens upstream. I will do it, but I really don't like having to support code that has nothing to do with *hyprscroller*. In my opinion there should be functions implemented in the support system (IHyprLayout) to call the relevant procedures depending on the type of layout and the type of window, otherwise things become very messy. But giving your insistence, I will commit those hacks today.

**Comment by dawsers** [comment]
Done in 733cfebfd241ecb98298314986896ad46dad3ccd
