### ISSUE TITLE
[Help] How to always center the focused window

### ISSUE THREAD

**Issue by Aman9das** [dawsers/hyprscroller#18]

**Comment by dawsers** [comment]
The focused window will only be centered when you open one in an empty workspace or use the center window dispatcher. When there are more than one window, *hyprscroller* doesn't center the focused window because it tries to fit more than that window in the monitor. But you can always use the dispatcher to do that (`scroller:alignwindow center`).

If you look at the example confguration, there is a `center` submap which I personally use:

```
# Center submap
# will switch to a submap called center
bind = $mainMod, C, submap, center
# will start a submap called "center"
submap = center
# sets repeatable binds for resizing the active window
bind = , C, scroller:alignwindow, c
bind = , C, submap, reset
bind = , right, scroller:alignwindow, r
bind = , right, submap, reset
bind = , left, scroller:alignwindow, l
bind = , left, submap, reset
bind = , up, scroller:alignwindow, u
bind = , up, submap, reset
bind = , down, scroller:alignwindow, d
bind = , down, submap, reset
# use reset to go back to the global submap
bind = , escape, submap, reset
# will reset the submap, meaning end the current one and return to the global one
submap = reset
```

If you press `mod + c` you enter that submap, and then pressing different keys will move the focused window to different positions, and align the rest relative to that. For example, `mod + c` and then `c` will center the window.

**Comment by Aman9das** [comment]
Hello! Running this script always centers the window when switching from one window to another:

```bash
handle() {
  	if [[ $1 == activewindowv2* ]]; then
  		hyprctl dispatch scroller:alignwindow c
      # hyprctl dispatch movecursor 960 540
  	fi
}

socat -U - UNIX-CONNECT:$XDG_RUNTIME_DIR/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock | while read -r line; do handle "$line"; done
```
