### ISSUE TITLE
Bug: focus cycling issue

### ISSUE THREAD

**Issue by aacebedo** [dawsers/hyprscroller#2]
It seems that focus cycles from the start of the windows list to the end works erratically. The cycle is not performing correctly when the last windows of the list is focused, and I try to focus to the right. Same for the left.

**Comment by dawsers** [comment]
Are you using `scroller:movefocus` in your key binding, or simply `movefocus`?

I explain in the README you need to use the `scroller` specific bindings beause Hyprland doesn't have a concept of windows outside of the monitor yet, so the default focus functions don't really work with this layout.

So, if I understand correctly, what you are seeing is because I am using the default `movefocus` to change monitors. When a window is "last" and you focus right, if there is another monitor on the right, the focus will move there. but if there is no monitor, the focus will move to the first full window of the current monitor that is inside the extents of the monitor. If you wanted to go to the first window of the Row, you would need to do a `scroller:movefocus begin`. The reason for this is the one I explained above, Hyprland doesn't think there are windows outside of the monitor, so when using `movefocus` it tries to find one in that direction, but inside the monitor. This could be a bug or a feature. On one hand, it is unexpected, on the other, it is useful. Let me explain. You can still go to the first/last columns by using `$mainMod begin/end` (in my case), but if you want to cycle within windows in the current view of the monitor, you can still do it because of this behavior.

Let me know what you think.

**Comment by aacebedo** [comment]
I am using the `scroller:movefocus` dispatcher.

I think I understood what you said about focus management but it leads to a very confusing behavior as I am unable to simply cycle through all windows of the row in both directions. 

I think I'll see two solutions here. Either detect in the `scroller:movefocus` dispatcher that you are located at the extremity of the Row it shall execute a `scroller:movefocus begin` or `end` depending on the side and direction. It could also be an option of the dispatcher to enable this behavior. However it won't solve the behaviour I have that I a m unable to scroll the entire row in both ways.

**Comment by dawsers** [comment]
Hyprland controls monitors, and the layout cannot do much without using code it shouldn't use. So the only solution I found to be able to move from one monitor to another transparently when at the edge, was to redirect `scroller:movefocus` to `movefocus` when at the beginning or end of the Row. If you have two monitors, this works well, it will move focus to the first window of the monitor in that direction. If you don't, that is when focusing doesn't "cycle", it just moves to the first/last window currently on screen. But you can still move to the beginning or end of the Row from any place, by using `scroller:movefocus begin/end`.
Calling `movefocus` is fire and forget, you have no control of what it will do, and it doesn't return any results you can evaluate, so what happened was it has that behavior of cycling, but within the windows that are currently on screen.

I am not sure I should work on this or maybe wait until Hyprland has support for layouts that span more than the screen extents.

I will leave it open, but I am not going to do anything at this time.

**Comment by aacebedo** [comment]
Ok noted. Is there already feature request opened in hyprland repo about that?

**Comment by dawsers** [comment]
I don't know, I haven't filed any issue there. I doubt they care about something like that when there is no official layout that needs such a feature. Unless people start using layouts like this one, there is no need to change the current behavior.

After I implement your feature request I will have a look at Hyperland's code again -now I know it a lot better- to see if I can do something simple.

**Comment by dawsers** [comment]
I fixed the "weird" focus behavior in fe3614410fe3169f7e31a50613b6c4a97d12442b. I am getting to know Hyprland's code better, and it was an easy change.
