### ISSUE TITLE
Window height unchanged on workspace resize

### ISSUE THREAD

**Issue by cpiber** [dawsers/hyprscroller#22]
If the available space changes (e.g. because the workspace is moved to another monitor), the window height is not adjusted. On my setup, this means if I move the workspace to the side monitor, the windows are too tall.

Moving the window to another workspace properly updates the height, but also resets the width.

**Comment by jonseppanen** [comment]
In addition to this, hyprscroller does not seem to respect multiple size options for gaps config in hypr. It only uses the first value even if there is multiple.

**Comment by dawsers** [comment]
What @cpiber describes is a bug, and I will try to fix it as soon as I have the time, probably this week. But multiple size gaps (different gap sizes on `top`, `bottom`, `left`, and `right`) will never be supported. Hyprland added this not too long ago, after I released the plugin, and my code is already messy enough to support different size desktop and window gaps to add even more complexity, so I decided having just one gap size per window should be enough for a scrolling layout. So right now, and in the future, the window gap size will be unique, and taken from the first value specified in the configuration.

**Comment by dawsers** [comment]
I have just committed a fix for this: 6254f9bb4e8d3a7f82651f88912fc374ac9b9948

It fixes the problem of resizing windows correctly when there is a call to `recalculateMonitor()` which happens when a workspace changes monitors or there are updates to bars etc. If the new viewport is different than the old one, now there is some logic to update all the windows to the correct sizes. The correct sizes are those given by `ColumnWidth` and `WindowHeight`, so when the window uses standard sizes (OneHalf, OneThird etc.), the window will be resized accordingly, but when the window has been resized manually, its size won't change.

However, for the second problem you mention, when moving a single window from one workspace to another, the window actually leaves the control of the layout. Hyprland calls `onWindowRemovedTiling()` to remove the window, and then `onWindowCreatedTiling()` to add it to the new workspace. So that is the reason why the window doesn't keep its width, it takes the default one, as hyprscroller considers it a new window (it left the layout before being added again). There could be some hacky ways to try to fix this, like storing a cache of windows that are no longer part of the layout, but I think that is not very clean, and could create other problems.

**Comment by cpiber** [comment]
> when moving a single window from one workspace to another, the window actually leaves the control of the layout

that makes sense, most of the time that limitation is also fine, it was just a bit annoying regarding the workspace resize :)

I updated the plugin, works quite nicely, thanks for the fix!
