### ISSUE TITLE
Is there anyway to not shrink size when `maximize` when there's window on the `prev` or `next` of the current active window?

### ISSUE THREAD

**Issue by ogios** [dawsers/hyprscroller#31]
![image](https://github.com/dawsers/hyprscroller/assets/96933655/1d4768dd-5859-437e-a7ff-172d349b4cd8)

sorry i didn't find where exactly this logic is in the code and it feels like it's related to a lot of code in different places

**Comment by dawsers** [comment]
That is because of the gaps setting. `gaps_in` is the gap between windows. `gaps_out` is the gap between windows and the monitor edges. So your maximized window will use a width of `viewport_width - 2 * gaps_out`, but if there are any windows at any side of it, they will be separated by `gaps_in`. That makes you see a bit of the window, like in your example. I also find it useful because it lets me know if there are more windows on the sides.

I know it doesn't work well for what you are trying to do with your shell, but it is the way it should be by definition of what gaps are.  I don't understand why you are trying to interact with the windows layer. When you create a layer shell window (like waybar or ags), you normally anchor it to some edge, and the compositor reserves that area. So the window layer (in this case hyprscroller) receives a message `recalculateMonitor()` and the area used by those *bars*, which can be located on any edge and any monitor, is already deducted from the `CMonitor` data, and not used by the windows layer. That is how we have bars as big as we want and they don't need to fight with the windows layer. That way you could get your own space there without any annoying windows showing up. You should also use a Z value that is on top of the layer, otherwise you would see pieces of windows as you do now.

Maybe I don't understand what you are trying to achieve, but my understanding is you want some kind of edge wigets, hot corners etc. So please enlighten me as to why you want to fight hyprscroller, as in the other warp cursor PR, which I have no problem with, of couse, but it serves a very specific purpose. Maybe we can find an easier and cleaner solution through the layer shell API. I am sure you have looked at AGS's code which also uses gtk-layer-shell, but if you haven't, maybe it can provide some insight. Or maybe I don't understand what you are trying to do.

**Comment by ogios** [comment]
Thanks! i'm learning rust by developing some tools i can use, what i'm actually trying to build is just put some hidden button on the edge of the screen and we can click it with different mouse button and trigger different events which including `hyprctl dispatch scroller::movefocus`.
If with `follow_mouse=1` i want to move focus to the window on the side, it will continuously move to the `beginning/end` of the `row/column`; And with `follow_mouse=2` i would have to click the window which result in a unwanted click event passed to that window. This is what bothering me and i didn't find any proper way dealing with it.
You are right, there could be a cleaner way, not to modify something for unrelated and specific purpose. i could just make a transparent surface and extend the input region to cover that area.

**Comment by dawsers** [comment]
Oh, I understand. The `follow_mouse` problem is quite annoying. There is a simple way to solve it. Just use a `gaps_in` value that is bigger than `gaps_out`, and you won't see any of the *prev* or *next* windows, and even with `follow_mouse = 1`, scrolling won't happen when at the edge of the monitor.
