### ISSUE TITLE
Weird behavior when opening windows in overview mode

### ISSUE THREAD

**Issue by skissue** [dawsers/hyprscroller#52]
1. Open a window on a workspace.
2. Enter overview mode.
3. Open another window.
4. Exit overview mode.
5. Window from step 3 acts weirdly.

I understand you're not supposed to do this, but perhaps the behavior could be a bit more robust to deal with when this accidentally happens. Maybe it should just exit overview mode if a new window appears?

**Comment by dawsers** [comment]
*overview* mode is just a simple scaling mode to overcome the fact that I cannot use Hyprland's renderer to prepare a view of the scaled windows and their content, as Hyprland doesn't support workspaces that cover more than the visible area of a monitor. The mode simply scales the window frames, but everything else remains the same size. I explain in the README that this "hack" should be used with caution. I don't want to remove it because I find it useful, but I don't want to have to check everywhere for possible use cases that I don't support.

In the README there is an example configuration to use *overview* without opening the possibility of creating new windows or making other mistakes like resizing windows etc. The workflow I use is very similar to that. Overview is a submap that only lets me do a few things and doesn't let me break things easily:

```
# overview keys
# bind key to toggle overview (normal)
bind = $mainMod, tab, scroller:toggleoverview
# bind mouse button to toggle overview
bind = ,mouse:275, scroller:toggleoverview
# overview submap
# will switch to a submap called overview
bind = $mainMod, tab, submap, overview
# will start a submap called "overview"
submap = overview
bind = , right, scroller:movefocus, right
bind = , left, scroller:movefocus, left
bind = , up, scroller:movefocus, up
bind = , down, scroller:movefocus, down
bind = CTRL, left, scroller:movewindow, l
bind = CTRL, right, scroller:movewindow, r
bind = CTRL, up, scroller:movewindow, u
bind = CTRL, down, scroller:movewindow, d
bind = CTRL, home, scroller:movewindow, begin
bind = CTRL, end, scroller:movewindow, end
# use reset to go back to the global submap
bind = , escape, scroller:toggleoverview,
bind = , escape, submap, reset
bind = , return, scroller:toggleoverview,
bind = , return, submap, reset
bind = $mainMod, tab, scroller:toggleoverview,
bind = $mainMod, tab, submap, reset
# will reset the submap, meaning end the current one and return to the global one
submap = reset
```

**Comment by skissue** [comment]
Ah, I understand. Thanks for the response and suggestion!
