### ISSUE TITLE
[Feature request] Add toggleadmissiondirection dispatcher

### ISSUE THREAD

**Issue by aacebedo** [dawsers/hyprscroller#7]
I think it would be great to have a dispatcher that change the admission direction of the windows.
For instance, if the admission direction is set to horizontal and you open or move a window, they simply keep the current behavior and are spawned between two windows horizontally. 
When the split direction is vertical, it would simply spawn the windows within the column of the current active window (a bit as the same behavior as the admitwindow dispatcher).

**Comment by dawsers** [comment]
Let me see if I understand this correctly...

You would like two modes to create windows. The first one (horizontal) is the current one: a new window is placed on a new column, located to the right of the active (focused) one. The second mode (vertical) would create a window right below the active one, but on the same column.

If I understand this correctly, you can simulate this now by creating the new window and calling `admitwindow` immediately after. It will place the window you just opened right below the one that was active before you opened it. You could even set a multi-action key binding to support that workflow.

Maybe I didn't understand what you suggest.

**Comment by aacebedo** [comment]
You understood what I meant correcly. My problem with your alternative solution is that when I start an app I use a launcher and I do not always want to be use one mode or the other.
Basically I was expecting a similar behavior to [hy3 ](https://github.com/outfoxxed/hy3/) `makegroup` dispatcher.

**Comment by dawsers** [comment]
That is very easy to implement. I am just worried about adding too many key bindings, but I will work on it. I want to re-work how windows are managed in Columns to make it more useful. I will add this feature then, when I have all the details figured out.

I accept suggestions. My current idea is leaning towards making column workflow similar to rows, with standard heights you can cycle, and a fitheight kind of dispatcher instead of the Auto and Free modes we have now. Lie I said, I am open to suggestions as I don't have any strong preferences right now. This also goes a bit in the direction of what @CRAG666 wants, but without changing the paradigm to a grid layout, which in my opinion has limitations, as columns and rows are "locked".

**Comment by dawsers** [comment]
With the new column rework, this should be completed

**Comment by DeepReef11** [comment]
Is it possible to make window spawn in opposite direction? For instance, new window would go up instead of down in  column mode. Same for moving window out of a column

**Comment by dawsers** [comment]
That would require quite a few changes in logic, because it is also expected that when you close a window, the new active one becomes the previous to the closed one, and similar logic happens in many more cases. That would need to be changed too depending on that special new mode or option.

You will need to make a strong case for me to implement such a mode, because I don't see it as something very useful for the amount of trouble. You can also try scripting something like that using IPC events if all you care is what happens at window creation (at `openwindow` call `movewindow` left or up depending on the current mode).

**Comment by DeepReef11** [comment]
For me, it just happen that the order of windows being spawn actually would be perfect if it was inverted. For instance, launching nvim then a terminal from cwd, the latest output on the terminal can be seen from the top screen but not from the bottom when window overflow screen so it needs to be bring back above nvim window. My secondary monitor is on the right, so I always want new row spawn to go to the left on primary screen. 

I don't think I have the time to put effort into that feature though.
