### ISSUE TITLE
Disabling hyprscroller Feature "gesture_scroll_enable" conflicts with Hyprland's "worskspace_swipe" 

### ISSUE THREAD

**Issue by BinaryInk** [dawsers/hyprscroller#73]
# System Info
```
OS: Arch Linux x86_64
Host: Surface Book 2
Kernel: Linux 6.11.4-arch1-1-surface
WM: Hyprland (Wayland)

Hyprland, built from branch  at commit 4520b30d498daca8079365bdb909a8dea38e8d55  (version: bump to 0.44.1).
Date: Wed Oct 9 12:54:39 2024
Tag: v0.44.1, commits: 5309
built against aquamarine 0.4.3
```

I'd run and test on 0.45, but as one of your other issues mentions, it is currently broken. At least: the release that was pushed out via the stable Arch repos the other day is broken to the point that even dwindle and master layouts won't work.

# Problem

When `gesture_scroll_enable` is disabled and  `workspace_swipe` is enabled, workspace swiping does not function. Instead of properly scrolling through to the next workspace, it will "partially" scroll to the next workspace, and then get stuck at the point my fingers leave the trackpad. 

Interestingly, as far as Hyprland is concerned, I'm still on the starting workspace and cursor actions will map to that "proper" positions on the starting workspace. Also an interesting quirk is that this only happens when swiping to the "next" workspace; no action occurs when trying to swipe to the "previous" workspace, though it *does* reset the visual glitch.

I have disabled the plugin entirely and `workspace_swipe` immediately works as intended; upon enabling again, it is broken, confirming it is the plugin causing the issue.

# Closing

1. This is a specific and minor issue, to me at least. For the time being I'll live with `gesture_scroll_enabled`.
2. If figuring this out requires time or de-prioritizes this issue due to a lack of hardware w/ a multi-touch trackpad for testing or anything along those lines, perfectly understandable.
3. This was a little difficult to explain, so hopefully this makes sense. Screensharing is broken on both my laptop and desktop's configs at the moment, so I can't get a screen recording via OBS. If I figure that out I can provide a video if my description doesn't suffice.

**Comment by dawsers** [comment]
While I look into it, I want to make sure you know *hyprscroller* also supports workspace swipes, by default with four fingers. Four fingers up/down toggle overview, four fingers right/left switch workspaces. So *hyprscroller* captures swipes with three fingers for scrolling, and four fingers for overview and workspace changes. Is there something there you think doesn't work well and prefer Hyprland's way of doing it? I want to make sure it is not a broken feature.

**Comment by dawsers** [comment]
fee68d961de81a4be7dcf04125ab5caaa5f371a7 disables `workspace_swipe` while in *hyprscroller*. I added an explanation to the README.

Basically, the way Hyprland's workspace swipe works is by moving the viewport while you swipe, from one workspace to the next. This works because in Hyprland windows don't exist outside of the viewport extents. In *hyprscroller* they do, so the animation would start showing windows on the original workspace but outside of the viewport, and suddenly stop, creating a mess of windows in limbo.

Good new is *hyprscroller* also has a workspace swipe gesture, and with the new `gesture_workspace_switch_prefix`, it should cover all the preferences for workspace switching.

**Comment by BinaryInk** [comment]
Aha, I was kind of wondering if it was connected to the way hyprscroller 'expanded' the workspace/desktop.

> I want to make sure you know hyprscroller also supports workspace swipes, by default with four fingers. 

I didn't know this...I'm fairly certain I tried with 4 fingers last night before submitting the issue, but not out of the realm of possibility I missed a setting or otherwise didn't trigger it... I'll give the updated readme another once over and try again a little later today.

Thanks again for the plugin (& your patience)

**Comment by BinaryInk** [comment]
Unfortunately, the problem persists with Hyprland 0.45.0. Same issue as described above.

Relevant configs:

```
gestures {
    workspace_swipe = false
    workspace_swipe_fingers = 3
    workspace_swipe_touch = false
}

plugin {
    scroller {
        # column_default_width = twothirds
        row_default_width = onehalf
        gesture_scroll_enable = false
        gesture_scroll_fingers = 4
        gesture_scroll_distance = 60
        gesture_overview_enable = false
        # gesture_overview_fingers = 4
        # gesture_overview_distance = 5
        gesture_workspace_switch_prefix = e
        gesture_workspace_switch_fingers = 3
        column_widths =  onethird onehalf twothirds
        row_widths = onethird onehalf twothirds one
    }
}
```
`gesture_workspace_switch_fingers` wasn't mentioned in the doc, but I tried it anyway in hopes that maybe that needed to be explicitly set if the setting exists--Hyprland didn't complain so it may be undocumented. Either way, doesn't matter if it's 3 or 4, workspace switching engages regardless of the setting with 3 or 4 fingers the way I have it configured above.

I can prioritize figuring out my screen recording issue later tonight if it would help.


Version info
```
Hyprland 0.45.0 built from branch  at commit a425fbebe4cf4238e48a42f724ef2208959d66cf  (version: bump to 0.45.0).
Date: Sat Nov 9 14:27:47 2024
Tag: v0.45.0, commits: 5433
built against aquamarine 0.5.0


flags set:
debug

OS: Arch Linux x86_64
Host: Surface Book 2 (124000000000000000000000D:0B:08K:1F:5C:10P:38)
Kernel: Linux 6.11.4-arch1-1-surface
```

**Comment by dawsers** [comment]
Your config is not correct. `gesture_overview_enable` enables or disables `overview` and workspace switching, as explained in the README.

So `gesture_scroll_*` are options for gesture scrolling, and `gesture_overview_*` are options for both `overview` and workspace switching, except `gesture_workspace_switch_prefix` which only makes sense for workspace switching.

As there are only usually 3 or 4 finger gestures available, I though combining overview and workspace switching made sense, because overview modes usually happen with up/down gestures (in other OSs), and workspace switching could use left/right. Instead scrolling needs the four directions, because you can scroll left/right, but also up/down.

So if you want to have everything enabled, you actually don't need to specify any options, the defaults are in the README, and they are enabled by default. Just set Hyprland's `workspace_swipe = false`, and *hyprscroller*'s gestures should work as explained in the README: 3 fingers for scrolling, and four for overview (up/down) and workspace switching (left/right).

Relevant part of the README: [gestures](https://github.com/dawsers/hyprscroller#gesture_scroll_enable)

**Comment by BinaryInk** [comment]
> I hope you are setting workspace_swipe = false into gestures, because that config setting changed.

> Today when I started playing around with it from a fresh boot, I had scroller:gesture_overview_enable = true, scroller:gesture_scroll_enable = true, and **hyprland:workspace_swipe = false.** gesture_scroll worked as expected, but there was no workspace switching with 4 fingers.

I'm going to be rebooting after this message with the following settings:

```
gestures {
    workspace_swipe = false
    workspace_swipe_fingers = 3
    workspace_swipe_touch = false
}

plugin {
    scroller {
        column_default_width = twothirds
        gesture_scroll_enable = true
        gesture_scroll_fingers = 3
        gesture_scroll_distance = 60
        gesture_overview_enable = true
        gesture_overview_fingers = 4
        gesture_overview_distance = 5
        gesture_workspace_switch_prefix = e
        column_widths = onethird onehalf twothirds
        row_widths = onethird onehalf twothirds
    }
}
```

**Comment by BinaryInk** [comment]
Yeah, I can confirm: swiping isn't working from a fresh boot. I swipe left or right now and `overview` is engaged (I didn't notice until I opened a second window in the workspace -- might want to prevent overview from activating in that instance?)

Interestingly, I'm not reproducing that 'bugged' swiping behavior toggling `hyprland:workspace_swipe` anymore.

**Comment by dawsers** [comment]
overview/swiping is quite sensitive as opposed to Hyprland's `workspace_swipe` where you need to do a long swipe.

You can modify the sensitivity of overview/workspace swiping by changing the `gesture_overview_distance` value. The default is just a flick of the fingers. Someone gave me a touchpad and I configured it to that one, but maybe yours needs a different sensitivity value.

**Comment by cpiber** [comment]
Sorry for entering this conversion with what may be unrelated info, but I've been following this for some time now.

I've noticed that workspace swipe is not working at all, and I think that `gesture_overview_distance` is not being considered for entering overview mode. No matter how lightly I touch the touchpad, it immediately enters overview, even when I try to swipe sideways for the here-mentioned workspace swipe.

Once I disabled `natural_scroll`, that suddenly changed and it workspace swipe seems to work. Maybe there's a flaw in the logic related to that?

That said, even when I enable `workspace_swipe` doesn't seem to change the behavior and it's working fine

**Comment by dawsers** [comment]
Thank you. That could be an explanation. My settings are these:

```
input {
    touchpad {
        natural_scroll = no
    }
}
```

So maybe I overlooked the case where `natural_scroll` is `true` for overview/workspace switching. I mainly tested scrolling. I will have a look at it.

I would also appreciate if any of you (with a different touchpad) could test with the settings above (`natural_scroll = no`) to discard any sensitivity problems, so I can set the default to a different value. I knew implementing gestures could open a can of works because of differences in hardware :-)

**Comment by cpiber** [comment]
Using `natural_scroll = no`, the default feels fine for the `gesture_overview_distance`. Somehow it feels a bit like I have to swipe farther left/right than up/down, which may be because it is wider? I also note that tweaking for touchpads/mouse input is quite normal, I also have Hyprland's sensitivity set to `-0.2` for the touchpad and `-0.9` for mouse, I don't think there's a default that works for everyone there

**Comment by cpiber** [comment]
Also, regarding the natural scroll, I think this line should be a multiplication, not addition:
https://github.com/dawsers/hyprscroller/blob/6eb99bbd00bbe3432ea29b4e64e8eed2603e1533/src/scroller.cpp#L3044

**Comment by dawsers** [comment]
Thank you for testing.

No, I believe the line you mention has to add all the deltas, because the swipe sends several events per swipe. You may want to scroll several windows and do a long swipe, so I get more than one event per swipe. That is why I have to keep adding them until the chosen trigger distance happens. But for overview, I only take the first event, because sensitivity is much higher (lower distance value), so the first swipe triggers it. There is probably a logic error there. I am having a look at it, but I need to set up debugging for that, because nesting Hyprland doesn't work well to debug touchpad events. So it will take me a bit longer, but I will have something today.

**Comment by dawsers** [comment]
To explain what I am doing:

- I get delta events, which is related to the length of the fingers moving on the touchpad. I get several of those per swipe.
- I check the addition of those deltas is higher than the trigger distance (the gesture distance option).
- For every trigger within a full swipe, there is a step (switch, window scrolling).
- But I need to keep the remainder in `gesture_delta`, because the next event will add to it.

**Comment by BinaryInk** [comment]
My next step was to use a clean config, but after playing with `natural_scroll` I think that's the crux of it. 

- I can second that turning off `natural_scroll` fixes it for me.
- I can also add that having `natural_scroll=true` and setting `gesture_overview_fingers=3` and `gesture_scroll_fingers=4` results in the same problem using 3 fingers for `gesture_overview` that exists with `gesture_overview_fingers=4`.

So, it doesn't appear to be an issue with the number of fingers, but just how `gesture_overview` and `natural_scroll` interact.

...I still can't explain some of the other oddities I ran into trying to figure it out, but I'm guessing those are edge-edge-edge cases from toggling various settings back and forth so much...

**Comment by BinaryInk** [comment]
Regarding sensitivity: doesn't seem to make any difference.

```
input {
    accel_profile = adaptive
    sensitivity = 0
}
```

Same results as I mentioned above when changing it to `0.5` and `-0.5` and toggling `natural_scroll`.

**Comment by dawsers** [comment]
I think eed0d58379f15db8d6d05fb485045933cd16d2fa should fix this.

Thank you both for all the help!

**Comment by BinaryInk** [comment]
Just chiming in since this thread was so long: That did indeed do the trick. Thanks once more!
