### ISSUE TITLE
[Question] Move windows between monitors

### ISSUE THREAD

**Issue by vncsalencar** [dawsers/hyprscroller#84]
Hi! I've been trying to setup a binding to move window between monitors, but I haven't been able to make it work.
I'm using the latest version of hyprland and hyprscroller. I tried the following:
`bind = $mainMod CTRL, h, scroller:movewindow, mon:HDMI-A-1`
and
`bind = $mainMod CTRL, h, movewindow, mon:HDMI-A-1`
But nothing works
Is there a way to achieve it?
Thanks in advance and sorry, I'm new to hyprland

**Comment by dawsers** [comment]
I didn't even know this dispatcher could take a monitor as an argument. So thanks to your message I have realized the functionality is broken. I will try to find a fix.

In the meantime, I suggest you use some variation of `movetoworkspace`, which will achieve a similar effect. Instead of moving a window to a monitor, it will move it to a workspace, focusing on a different monitor if that is where the workspace is.:

```
# Move active window to a workspace with mainMod + SHIFT + [0-9]
bind = $mainMod SHIFT, 1, movetoworkspace, 1
bind = $mainMod SHIFT, 2, movetoworkspace, 2
bind = $mainMod SHIFT, 3, movetoworkspace, 3
bind = $mainMod SHIFT, 4, movetoworkspace, 4
bind = $mainMod SHIFT, 5, movetoworkspace, 5
bind = $mainMod SHIFT, 6, movetoworkspace, 6
bind = $mainMod SHIFT, 7, movetoworkspace, 7
bind = $mainMod SHIFT, 8, movetoworkspace, 8
bind = $mainMod SHIFT, 9, movetoworkspace, 9
bind = $mainMod SHIFT, 0, movetoworkspace, 10
```

**Comment by dawsers** [comment]
The fix was simpler than I thought. It's here cead619172e9b64d1f84dbb4d030277c435e382f

Update to the latest version and it should work. Use Hyprland's default dispatcher:

```
 bind = $mainMod CTRL, h, movewindow, mon:HDMI-A-1
```

**Comment by vncsalencar** [comment]
Thanks! @dawsers I'll test later today, but appreciate your quick reply and fix (lol)
