### ISSUE TITLE
[Feature Request] `cyclewidth` and `cycleheight`

### ISSUE THREAD

**Issue by MattKang** [dawsers/hyprscroller#88]
Would love to have a way to separately cycle column widths and window heights.

Been really loving the plugin. I think the 2D nature of hyprscroller is a huge improvement over PaperWM, and I've been leveraging it quite a bit. Honestly, I would not be using hyprland if not for hyprscroller.

I currently bind `cyclesize` to `Super + R`, and it would be great to instead have:
- `cyclewidth` -> `Super + R`
- `cycleheight` -> `Super + Shift + R`

Would make it easier to quickly resize windows without having to cycle through row/column mode.

Happy to help contribute to this feature if desired.

**Comment by dawsers** [comment]
Thank you.

I think it is a reasonable request. The current system predates *column mode*, so I adapted it. I will implement the feature. I am running out of keys for so many bindings, though! :-)

I understand most people only use a subset of *hyprscroller* that fits their workflow, but I try to keep all the dispatchers assigned to some binding so I can test, an also because at some point, every feature made sense...so I am going to need a special keyboard on the side or something like that :-)

**Comment by dawsers** [comment]
I added this in f252d34cbf927004ed33d2ffeee233ece9e3d488

Thanks for the suggestion.
