### ISSUE TITLE
[Features]  cyclemode, disable wrap, admit/expel direction

### ISSUE THREAD

**Issue by Acumane** [dawsers/hyprscroller#9]
Thank you for this plugin! I'm pretty close to daily driving it. Before I open individual tickets, here's some points of improvement in order of personal preference:

- Seeing as there's only two modes (row/col), it makes more sense to cycle between them. 
`bindr = SUPER SHIFT, SUPER_L, scroller:cyclemode`

- Wraparound can be disorienting, esp. with no/fast animations
`plugin:scroller { wrap = <bool> }` would be nice

- Add direction to admit/expel. This might complicate the current experience so thought I'd float it past you first.

**Comment by dawsers** [comment]
I am glad you are finding it useful.

About row/col cyclemode, because there is no feedback on which mode you are on (column/row), I found easier to simply not use "cyclemode". That's the way it used to worked when I first implemented the feature, but I removed it because I found myself often forgetting which mode was on, so I would end up opening the window in the "wrong" position. The way it works now, when I am in doubt, I press the key to toggle the mode I want before opening a new window. I have the two keys next to each other, so it really doesn't add a lot of friction vs having a "cycle" mode where I would need to remember the mode after maybe a long time without opening any windows. I thought of implementing an IPC facility to output data so it could be displayed by the "bar", but then I would need to write modules for every available bar, so I decided against it.

It's funny wrapping is so polarizing. I can probably add an option to disable it. Personally, I use two monitors, so the default way allows me to move from one monitor to the next easily. And then there is SUPER+Home/END to quickly fix a mistake. I will look into it.

I am usually against options that add a lot of thinking to what comes next when I press a key, I'd rather think on what I am working on. Admit/Expel is predictable, and using it together with row/column mode and moving windows, you can achieve almost anything, though maybe you need a couple of key presses more. I find I am running out of spare keys for so many bindings, so I end up having to use submaps, which are cool, but add another key press...so it is a tough choice, sometimes having too many features that are not really needed doesn't help productivity.

**Comment by dawsers** [comment]
I added a `focus_wrap` option to control the focusing behavior in fa8f73e81e3bd7d503f12b3568000460781ba2a9

I don't think I am going to change to a "cycling" mode for rows/columns instead of having the two dispatchers we have now. The reasons are the ones I explained in the previous comment. It just doesn't work for me.

So I think for now I can close this issue. Of course, feel free to open a new one with any other concerns.

**Comment by Acumane** [comment]
[setmode cycle script](https://github.com/Acumane/dotfiles/blob/linux/scripts/setmode)

Also, thoughts on this? :point_down: 
> My only use case for staying in column mode would be for vertical monitors—this might even be an expected default behavior.

**Comment by dawsers** [comment]
I agree people with vertical monitors will probably want to use column mode as default, and there is nothing preventing them to do so. As soon as they create the first window, they just need to press the column mode shortcut.

I have two monitors, both in horizontal mode, and I also use columns for similar windows I may want to have close to the columns on their side. The truth is *hyprscroller* has around 10 users on a good day, so I don't want to spend too much time adding edge cases nobody really cares about. I wrote it for myself, and I am glad some other people find it useful. I was using PaperWM on GNOME, but wanted to try Hyprland. I really liked Hyprland, but the available layouts were not what I wanted. I found *hyprslidr* when searching for a PaperWM-like alternative, but it was still quite green, so I wrote this plugin. It does almost all I want it to do, and I have been using it continuously since I moved to Hyprland last month.

So the goal of the project at this point is to, of course, fix any bugs people find, and add small things I may be needing as time goes by. Also, if someone has an idea I like, I will implement it. But I am not going to be chasing things nobody cares about (again, around 10 users) just for the sake of "correctness".

Of course, I am really thankful you are taking the time to analyze *hyprscroller* and even thinking of becoming one of its users.
