### ISSUE TITLE
Single window not getting recentered in multiple scenarios

### ISSUE THREAD

**Issue by Kasper24** [dawsers/hyprscroller#91]
Right now, if you open the first window in the workspace it will be correctly centered, but in some certain scenarios this can break:

- Resizing of a single window, the window does not get recentered
- 2 windows on the same workspace, close 1 window - the single window does not get recentered.
- 2 windows on the same workspace, move 1 window to another workspace - the single window on the workspace you moved the second window from does not get recentered.
- 2 windows on the same workspace, toggle one as floating - the single tiled window 
does not get recentered.

**Comment by dawsers** [comment]
You are right, the only time a window is centered is when it is the first one opened, or if you explicitly center it using `alignwindow` as a dispatcher or window rule. This is by design. Column recalculation is "semi-lazy". Windows don't move as long as there is no "benefit" in their movement. Benefit means in this case that by their movement, another column/window may fit the monitor.

This is explained here: https://github.com/dawsers/hyprscroller/issues/18

In that issue, there is also a script if you want to center windows automatically.

There is also a [window rule](https://github.com/dawsers/hyprscroller#window-rules) `alignwindow` you can use to auto-center any window you want.

**Comment by Kasper24** [comment]
Thanks for the quick answer! The issue is that #18 doesn't help with the scenarios I had described below. I have an ultrawide, so having a single window on the side of the monitor is a little awkward.
Right now I'm using this shell script to help mitigate this, but the issue this doesn't work for the scenario where I have 2 tiled windows, and then I float one - because I can't retrieve the number of tiled windows only
```
hyprctl dispatch ${action}
sleep 0.1
layout=$(hyprctl -j getoption general:layout | ${pkgs.jq}/bin/jq -r '.str' | sed 's/"//g' )
 windows_count=$(hyprctl activeworkspace -j | ${pkgs.jq}/bin/jq -r '.windows' )
if [[ $layout = "scroller" && $windows_count -eq 1 ]]; then
  hyprctl dispatch scroller:alignwindow c
fi
```

**Comment by dawsers** [comment]
For that case, you will need to manually center the remaining, non-floating window using `alignwindow`. For example:

```
bind = $mainMod, c, scroller:alignwindow, c
```

or more generally:

```
# Align submap
# will switch to a submap called align
bind = $mainMod, C, submap, align
# will start a submap called "align"
submap = align
# sets repeatable binds for aligning the active window
bind = , c, scroller:alignwindow, c
bind = , c, submap, reset
bind = , m, scroller:alignwindow, m
bind = , m, submap, reset
bind = , right, scroller:alignwindow, r
bind = , right, submap, reset
bind = , left, scroller:alignwindow, l
bind = , left, submap, reset
bind = , up, scroller:alignwindow, u
bind = , up, submap, reset
bind = , down, scroller:alignwindow, d
bind = , down, submap, reset
# use reset to go back to the global submap
bind = , escape, submap, reset
# will reset the submap, meaning end the current one and return to the global one
submap = reset
```

If I automatically centered windows instead of leaving where they are (unless in the cases explained in the previous post), things would be less predictable. For example, you like centering when there is just one window, but some people might also want centered windows when there are two (also ultra-wide monitor), or when all the windows fit the screen and leave some space. I could add another dispatcher for that, but it wouldn't be automatic, you would still need to hit some key combination, like you do now. That is probably a good idea, something like `alignwindow all` or similar.

Also, when you float a window and one of the combinations I explained happens (one window left, two windows left, free space in the viewport), if I centered the remaining windows, their position with respect to the floating window would change any time you resize, add a window, or move or remove one of them. This would create changes in visibility, as things move around . Right now, things are predictable. You set your windows, and as long as they all fit the monitor, they won't move, so you can position your floating window in some space left by them, or cover whichever window you like.

**Comment by Kasper24** [comment]
I understand your motivation for this, but this is what all the other scrolling WMs are doing (KDE Karousel, Gnome PaperWM, Niri). Is there any chance adding it as a config option?

**Comment by dawsers** [comment]
What would the option do? Center windows when there is just one, when there are more, when every window fits the monitor leaving extra space? PaperWM has a focus mode where they center any window when it's focused, regardless of number or coverage. Karousel centers the group of windows like the `alignwindow all` I mentioned. So it would be good to define what that option would do.

**Comment by Kasper24** [comment]
In Karousel a single window will always get centered.
In Niri, you have an option to set to a single window will always be centered.
PaperWM I might have been wrong about, it's been a bit since I've last used it.

I could actually implement this behavior in a bash script, by parsing the output of various hyprctl commands, but the issue I'm facing right now is that the scroller:alignwindow dispatcher only allows for setting the alignment of the active window, would it be possible to make so we can also pass in the window?

**Comment by dawsers** [comment]
I have only used PaperWM of the three you mentioned. I actually wrote *hyprscroller* when I moved to Hyprland because I missed PaperWM. So I watched the video in Karousel's site, and it seems it centers the stripe of windows whenever there is free space on their sides. That means it will center a single window, or any number of them as long as all the windows in the workspace fit the monitor. Would that be enough for your use case? You will get a single window centered, but if you open a second one and there is still free space, the set of windows will be centered too. This to me makes more sense than only centering when there is one window.

**Comment by Kasper24** [comment]
Yeah, this is the behavior I'm used to from other WMs. I guess it matters less when you use a regular monitor, but for ultrawides the current logic is a little awkward I feel like.
The bash script from above gets me halfway there, but if you could actually add this behavior as an option that would be amazing. I'd have made a PR for that instead, but I'm afraid my Hyprland knowledge is a little lacking.

**Comment by dawsers** [comment]
OK, I will add an option to do that. I am currently rewriting some of the ordering logic, so I will add it once it's done. It may take a couple of days. I will reopen this issue to track it.

Thanks for the suggestion.

**Comment by Kasper24** [comment]
Thanks!
