### ISSUE TITLE
scroller:cyclewidth and scroller:cycleheight dispatchers do not exist

### ISSUE THREAD

**Issue by DJNighswander** [dawsers/hyprscroller#92]
I was trying out the different dispatcher calls while setting up my config when I noticed that the scroller:cycleheight and scroller:cyclewidth dispatchers appear to not exist even though they are listed in the documentation. I've attempted to call both the dispatchers via binds as well as via hyprctl and neither seem to work.

**Comment by dawsers** [comment]
You are probably using an older version of the plugin that doesn't include those dispatchers. They were introduced in https://github.com/dawsers/hyprscroller/issues/88, on Nov 29.

You have two options, either update the plugin or use the old dispatcher `scroller:cyclesize` which applies to the current mode you are in (row or column).

Your plugin may be outdated because you use a version included with your Linux distribution. For example, if you are on NixOS, it was last updated on Nov 29, so it would include the feature if you update to the latest version. If you are on a more traditional Linux distribution, I recommend you use `hyprpm` to install and manage the plugin (as [explained in the README](https://github.com/dawsers/hyprscroller#hyprpm)):

```
hyprpm update
hyprpm add https://github.com/dawsers/hyprscroller
# verify it installed correctly
hyprpm list
hyprpm enable hyprscroller
```

Then add these to your config:

```
exec-once = hyprpm reload -n
general {
    ...

    layout = scroller

    ...
}
```

Using `hyprpm` will make it easier to stay up to date with the latest features and bug fixes.

**Comment by DJNighswander** [comment]
I've got hyprscroller installed via hyprpm as current as of yesterday and was still having the issue. Would hyprpm's  --no-shallow flag cause it? That was the only thing I had to do different from the standard install.

**Comment by dawsers** [comment]
I don't know. If I were you, I would remove `hyprpm`'s cache and re-install:

```
rm -rf ~/.local/share/hyprpm
hyprpm update
hyprpm add https://github.com/dawsers/hyprscroller
hyprpm enable hyprscroller
```

And then verify you are loading the plugin using `hyprpm` (check your configuration to make sure you don't have any `plugin` statement that references `hyprscroller`), and that you don't have it installed anywhere else.

**Comment by dawsers** [comment]
Of course, for this to work, you need to be running Hyprland v0.45 or later. If your version is older, `hyprpm` will compile an older version of the plugin to match your version of Hyprland.

**Comment by DJNighswander** [comment]
Ahh, that would be it. I'm on Void Linux which is lagging behind on GCC 14 so it's still on hyprland 0.44.1. I guess I'm stuck waiting for now.
