### ISSUE TITLE
Disable edge jumping

### ISSUE THREAD

**Issue by wylited** [dawsers/hyprscroller#98]
Hi, really love hyprscroller but I tend to sometime overshoot when moving my mouse to the left or right and this causes it to move the focus to the respective direction which is really annoying.

Is there any way to disable this.

**Comment by dawsers** [comment]
Yes. If you use a `gaps_out` on the right and left smaller than `gaps_in`, you won't see the edge of the windows that are right outside of the viewport, so even if you use `follow_mouse = 1` for focus, there will be no window to focus on when your mouse is at the edge, and you won't get that annoying refocusing. This is what I use:

```
general {
    # By having a gaps_out smaller than gaps_in, the 'prev' or 'next' window
    # is not seen at all, so you can use follow_mouse = 1 and scrolling won't
    # happen when the mouse is at the edge of the monitor.
    gaps_in = 5
    gaps_out = 10, 4, 10, 4
    border_size = 2
....
```

**Comment by BinaryInk** [comment]
Adding to this...I kind of enjoy having the edges appearing when it's off-screen, as it's a reminder that there's a window off-screen; however, I, too, am annoyed by the focus issue as described (especially on a 2+ monitor setup).

Is it possible to 'shrink' the activation focus window by a few pixels (perhaps definable in the plugin config) or would that be incredibly difficult and/or hacky, which could result in maintainability issues from version to version of Hyprland?

(I've been on the fence asking about this because I assume it's probably not feasible even if possible, but since the subject's been broached I may as well make the ask)

**Comment by dawsers** [comment]
This is not a plugin issue. Focusing is controlled by Hyprland. I would need to hack into the mouse/tablet/keyboard/etc. input and override those Hyprland functions. The workaround is to either do what I explained above, or use another focus mode that doesn't follow the pointer.

**Comment by BinaryInk** [comment]
No worries--I figured that was _very_ likely the case. Appreciate the response nevertheless

**Comment by dawsers** [comment]
There is an option now after 686bf83316be96cbaed980b63ad43514cf0dce3c

It is on by default, with a timeout value of 400 ms. More details in the [README](https://github.com/dawsers/hyprscroller#focus_edge_ms)
